// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1518.robot;



import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.interfaces.Gyro;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.BuiltInAccelerometer;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Solenoid;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
		//Drive Train
			//Test Robot
	public static WPI_TalonSRX testdriveTrainFrontLeftWheel;
	public static WPI_TalonSRX testdriveTrainFrontRightWheel;
	public static WPI_TalonSRX testdriveTrainRearLeftWheel;
	public static WPI_TalonSRX testdriveTrainRearRightWheel; 
	
			//Main Robot
	public static WPI_VictorSPX driveTrainFrontLeftWheel;
	public static WPI_VictorSPX driveTrainFrontRightWheel;
	public static WPI_VictorSPX driveTrainRearLeftWheel;
	public static WPI_VictorSPX driveTrainRearRightWheel;
	
		//Aux Controllers
				//Main Robot
	public static WPI_TalonSRX lift;
	public static WPI_TalonSRX climb;
	
				//Test Robot
	public static VictorSP testlift;
	//public static VictorSP testclimb;
	
		//Solenoids
	public static Solenoid solenoid0;
	public static Solenoid solenoid1;
	public static Solenoid solenoid2;
	public static Solenoid solenoid3;
	public static Solenoid solenoid4;
	public static Solenoid solenoid5;
	
		//Limit Switches
	public static DigitalInput BoxSwitch;
	public static DigitalInput ClimbSwitch;


		//Encoders
	public static Encoder encoderLRear;
	public static Encoder encoderRRear;
	
		//Digital Outputs
	public static DigitalOutput dio8;
	public static DigitalOutput dio9; 
	
		//Other
	public static Gyro rioGyro;
	public static BuiltInAccelerometer rioAccel;
	public static Compressor comp0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
    		//Drive Train
    				//Main Robot
    	driveTrainFrontLeftWheel = new WPI_VictorSPX(1);
    	driveTrainFrontRightWheel = new WPI_VictorSPX(2);
    	driveTrainRearRightWheel = new WPI_VictorSPX(3);
    	driveTrainRearLeftWheel = new WPI_VictorSPX(4);
    	
    				//Test Robot
    	testdriveTrainFrontLeftWheel = new WPI_TalonSRX(1);
    	testdriveTrainFrontRightWheel = new WPI_TalonSRX(2);
    	testdriveTrainRearRightWheel = new WPI_TalonSRX(3);
    	testdriveTrainRearLeftWheel = new WPI_TalonSRX(4);
    		//Encoders
    	encoderLRear = new Encoder(0, 1, true, Encoder.EncodingType.k1X);
    	encoderRRear = new Encoder(2, 3, false, Encoder.EncodingType.k1X);
    	
    	
    		//Aux controllers
    			//Climb
    					//Main Robot
    	climb = new WPI_TalonSRX(6);
    	//climb.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Absolute, 0, 1);
    	
    					//Test Robot
    	//climb = new VictorSP(0);
    	
    			//Lift
						//Main Robot
    	lift = new WPI_TalonSRX(5);
    	//lift.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Absolute, 2, 3);

    					//Test Robot
    	testlift = new VictorSP(0);

    		// Pneumatics
    	comp0 = new Compressor(0);
    	solenoid0 = new Solenoid(0);
    	solenoid1 = new Solenoid(1);
    	solenoid2 = new Solenoid(2);
    	solenoid3 = new Solenoid(3);
    	solenoid4 = new Solenoid(4);
    	solenoid5 = new Solenoid(5);

    		//Digital outputs for LEDs.
    	dio8 = new DigitalOutput(8);
    	dio9 = new DigitalOutput(9);

    		//Limit Switches
    	BoxSwitch = new DigitalInput(4);
    	ClimbSwitch = new DigitalInput(5);


			//Gyro 
		rioGyro = new ADXRS450_Gyro();
		rioAccel = new BuiltInAccelerometer();
    	
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
