// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1518.robot;




import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.interfaces.Gyro;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.AnalogAccelerometer;
import edu.wpi.first.wpilibj.BuiltInAccelerometer;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Talon;


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static WPI_TalonSRX driveTrainFrontLeftWheel;
	public static WPI_TalonSRX driveTrainFrontRightWheel;
	public static WPI_TalonSRX driveTrainRearLeftWheel;
	public static WPI_TalonSRX driveTrainRearRightWheel; 
	public static Encoder frontLeftEnc;
	public static WPI_TalonSRX shooterMotor;
	public static Servo servo1;
	public static Servo servo2;
	public static VictorSP intakeMotor;
	public static WPI_TalonSRX feedMotor1;
	public static WPI_TalonSRX feedSpare1;
	public static VictorSP shootAgitator;
	public static WPI_TalonSRX lift;
	public static Solenoid solenoid0;
	public static Solenoid solenoid1;
	public static Solenoid solenoid2;
	public static Solenoid solenoid3;
	public static Solenoid solenoid4;
	public static Solenoid solenoid5;
	public static Talon pwmDriveFL;
	public static Talon pwmDriveRL;
	public static Talon pwmDriveFR;
	public static Talon pwmDriveRR;
	public static Talon pwmShooter;
	public static Talon pwmFeeder;
	public static Talon pwmIntake;
	public static DigitalOutput dio8;
	public static DigitalOutput dio9; 
	public static Gyro rioGyro;
	public static BuiltInAccelerometer rioAccel;
	public static VictorSP pwmLift;
	public static Compressor comp0;
	//public static Talon pwmWinch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        //Real bot drive motors
    	driveTrainFrontLeftWheel = new WPI_TalonSRX(1);
    	driveTrainFrontRightWheel = new WPI_TalonSRX(2);
    	driveTrainRearRightWheel = new WPI_TalonSRX(3);
    	driveTrainRearLeftWheel = new WPI_TalonSRX(4);
    	// Set Follower Mode on rear motors
    	//driveTrainRearLeftWheel.changeControlMode(CANTalon.TalonControlMode.Follower);
    	//driveTrainRearLeftWheel.set(4);
    	//driveTrainRearRightWheel.changeControlMode(CANTalon.TalonControlMode.Follower);
    	//driveTrainRearRightWheel.set(1);
    	//frontLeftEnc = new Encoder(10, 11, false, Encoder.EncodingType.k1X);
    	//Shooter subsystem
    	shooterMotor = new WPI_TalonSRX(6);
    	shootAgitator = new VictorSP(7);
    	intakeMotor = new VictorSP(2);
    	feedMotor1 = new WPI_TalonSRX(8);
    	feedSpare1 = new WPI_TalonSRX(5);
    	lift = new WPI_TalonSRX(9);
    	pwmFeeder = new Talon(8);
    	//pwmWinch = new Talon(9);
    	//pwmIntake = new Talon(3);
    	servo1 = new Servo(0);
    	servo2 = new Servo(1);
    	//Redundant pneumatics code.
    	comp0 = new Compressor(0);
    	solenoid0 = new Solenoid(0);
    	solenoid1 = new Solenoid(1);
    	solenoid2 = new Solenoid(2);
    	solenoid3 = new Solenoid(3);
    	solenoid4 = new Solenoid(4);
    	solenoid5 = new Solenoid(5);
    	//Digital outputs for LEDs.
    	dio8 = new DigitalOutput(8);
    	dio9 = new DigitalOutput(9);
    	pwmLift = new VictorSP(9);

		//Gyro 
		rioGyro = new ADXRS450_Gyro();
		rioAccel = new BuiltInAccelerometer();

		//Testbot motor setup.
    	//pwmDriveFL.setInverted(true);
    	//pwmDriveRL.setInverted(true);
    	//pwmDriveFR.setInverted(true);
    	//pwmDriveRR.setInverted(true);
    	
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
